//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PersonalInventory.UPCSearch {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://searchupc.com/", ConfigurationName="UPCSearch.UPCSearchSoap")]
    public interface UPCSearchSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://searchupc.com/GetProduct", ReplyAction="*")]
        System.IAsyncResult BeginGetProduct(PersonalInventory.UPCSearch.GetProductRequest request, System.AsyncCallback callback, object asyncState);
        
        PersonalInventory.UPCSearch.GetProductResponse EndGetProduct(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://searchupc.com/GetProductJSON", ReplyAction="*")]
        System.IAsyncResult BeginGetProductJSON(PersonalInventory.UPCSearch.GetProductJSONRequest request, System.AsyncCallback callback, object asyncState);
        
        PersonalInventory.UPCSearch.GetProductJSONResponse EndGetProductJSON(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://searchupc.com/Validate", ReplyAction="*")]
        System.IAsyncResult BeginValidate(PersonalInventory.UPCSearch.ValidateRequest request, System.AsyncCallback callback, object asyncState);
        
        PersonalInventory.UPCSearch.ValidateResponse EndValidate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://searchupc.com/ConvertToUPCA", ReplyAction="*")]
        System.IAsyncResult BeginConvertToUPCA(PersonalInventory.UPCSearch.ConvertToUPCARequest request, System.AsyncCallback callback, object asyncState);
        
        PersonalInventory.UPCSearch.ConvertToUPCAResponse EndConvertToUPCA(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://searchupc.com/GenerateBarcode", ReplyAction="*")]
        System.IAsyncResult BeginGenerateBarcode(PersonalInventory.UPCSearch.GenerateBarcodeRequest request, System.AsyncCallback callback, object asyncState);
        
        PersonalInventory.UPCSearch.GenerateBarcodeResponse EndGenerateBarcode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://searchupc.com/SuggestProduct", ReplyAction="*")]
        System.IAsyncResult BeginSuggestProduct(PersonalInventory.UPCSearch.SuggestProductRequest request, System.AsyncCallback callback, object asyncState);
        
        PersonalInventory.UPCSearch.SuggestProductResponse EndSuggestProduct(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProduct", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.GetProductRequestBody Body;
        
        public GetProductRequest() {
        }
        
        public GetProductRequest(PersonalInventory.UPCSearch.GetProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GetProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accesstoken;
        
        public GetProductRequestBody() {
        }
        
        public GetProductRequestBody(string upc, string accesstoken) {
            this.upc = upc;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductResponse", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.GetProductResponseBody Body;
        
        public GetProductResponse() {
        }
        
        public GetProductResponse(PersonalInventory.UPCSearch.GetProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GetProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProductResult;
        
        public GetProductResponseBody() {
        }
        
        public GetProductResponseBody(string GetProductResult) {
            this.GetProductResult = GetProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductJSON", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.GetProductJSONRequestBody Body;
        
        public GetProductJSONRequest() {
        }
        
        public GetProductJSONRequest(PersonalInventory.UPCSearch.GetProductJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GetProductJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accesstoken;
        
        public GetProductJSONRequestBody() {
        }
        
        public GetProductJSONRequestBody(string upc, string accesstoken) {
            this.upc = upc;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductJSONResponse", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.GetProductJSONResponseBody Body;
        
        public GetProductJSONResponse() {
        }
        
        public GetProductJSONResponse(PersonalInventory.UPCSearch.GetProductJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GetProductJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProductJSONResult;
        
        public GetProductJSONResponseBody() {
        }
        
        public GetProductJSONResponseBody(string GetProductJSONResult) {
            this.GetProductJSONResult = GetProductJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(PersonalInventory.UPCSearch.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accesstoken;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(string upc, string accesstoken) {
            this.upc = upc;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(PersonalInventory.UPCSearch.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(string ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToUPCARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToUPCA", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.ConvertToUPCARequestBody Body;
        
        public ConvertToUPCARequest() {
        }
        
        public ConvertToUPCARequest(PersonalInventory.UPCSearch.ConvertToUPCARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class ConvertToUPCARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upce;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accesstoken;
        
        public ConvertToUPCARequestBody() {
        }
        
        public ConvertToUPCARequestBody(string upce, string accesstoken) {
            this.upce = upce;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToUPCAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToUPCAResponse", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.ConvertToUPCAResponseBody Body;
        
        public ConvertToUPCAResponse() {
        }
        
        public ConvertToUPCAResponse(PersonalInventory.UPCSearch.ConvertToUPCAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class ConvertToUPCAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertToUPCAResult;
        
        public ConvertToUPCAResponseBody() {
        }
        
        public ConvertToUPCAResponseBody(string ConvertToUPCAResult) {
            this.ConvertToUPCAResult = ConvertToUPCAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateBarcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateBarcode", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.GenerateBarcodeRequestBody Body;
        
        public GenerateBarcodeRequest() {
        }
        
        public GenerateBarcodeRequest(PersonalInventory.UPCSearch.GenerateBarcodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GenerateBarcodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        public GenerateBarcodeRequestBody() {
        }
        
        public GenerateBarcodeRequestBody(string upc) {
            this.upc = upc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateBarcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateBarcodeResponse", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.GenerateBarcodeResponseBody Body;
        
        public GenerateBarcodeResponse() {
        }
        
        public GenerateBarcodeResponse(PersonalInventory.UPCSearch.GenerateBarcodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GenerateBarcodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateBarcodeResult;
        
        public GenerateBarcodeResponseBody() {
        }
        
        public GenerateBarcodeResponseBody(string GenerateBarcodeResult) {
            this.GenerateBarcodeResult = GenerateBarcodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestProduct", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.SuggestProductRequestBody Body;
        
        public SuggestProductRequest() {
        }
        
        public SuggestProductRequest(PersonalInventory.UPCSearch.SuggestProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class SuggestProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productnamewithmanufacturer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string productattribute;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accesstoken;
        
        public SuggestProductRequestBody() {
        }
        
        public SuggestProductRequestBody(string upc, string productnamewithmanufacturer, string productattribute, string accesstoken) {
            this.upc = upc;
            this.productnamewithmanufacturer = productnamewithmanufacturer;
            this.productattribute = productattribute;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestProductResponse", Namespace="http://searchupc.com/", Order=0)]
        public PersonalInventory.UPCSearch.SuggestProductResponseBody Body;
        
        public SuggestProductResponse() {
        }
        
        public SuggestProductResponse(PersonalInventory.UPCSearch.SuggestProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class SuggestProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SuggestProductResult;
        
        public SuggestProductResponseBody() {
        }
        
        public SuggestProductResponseBody(string SuggestProductResult) {
            this.SuggestProductResult = SuggestProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCSearchSoapChannel : PersonalInventory.UPCSearch.UPCSearchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertToUPCACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConvertToUPCACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerateBarcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GenerateBarcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuggestProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SuggestProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCSearchSoapClient : System.ServiceModel.ClientBase<PersonalInventory.UPCSearch.UPCSearchSoap>, PersonalInventory.UPCSearch.UPCSearchSoap {
        
        private BeginOperationDelegate onBeginGetProductDelegate;
        
        private EndOperationDelegate onEndGetProductDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductJSONDelegate;
        
        private EndOperationDelegate onEndGetProductJSONDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductJSONCompletedDelegate;
        
        private BeginOperationDelegate onBeginValidateDelegate;
        
        private EndOperationDelegate onEndValidateDelegate;
        
        private System.Threading.SendOrPostCallback onValidateCompletedDelegate;
        
        private BeginOperationDelegate onBeginConvertToUPCADelegate;
        
        private EndOperationDelegate onEndConvertToUPCADelegate;
        
        private System.Threading.SendOrPostCallback onConvertToUPCACompletedDelegate;
        
        private BeginOperationDelegate onBeginGenerateBarcodeDelegate;
        
        private EndOperationDelegate onEndGenerateBarcodeDelegate;
        
        private System.Threading.SendOrPostCallback onGenerateBarcodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginSuggestProductDelegate;
        
        private EndOperationDelegate onEndSuggestProductDelegate;
        
        private System.Threading.SendOrPostCallback onSuggestProductCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public UPCSearchSoapClient() {
        }
        
        public UPCSearchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCSearchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCSearchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCSearchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetProductCompletedEventArgs> GetProductCompleted;
        
        public event System.EventHandler<GetProductJSONCompletedEventArgs> GetProductJSONCompleted;
        
        public event System.EventHandler<ValidateCompletedEventArgs> ValidateCompleted;
        
        public event System.EventHandler<ConvertToUPCACompletedEventArgs> ConvertToUPCACompleted;
        
        public event System.EventHandler<GenerateBarcodeCompletedEventArgs> GenerateBarcodeCompleted;
        
        public event System.EventHandler<SuggestProductCompletedEventArgs> SuggestProductCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PersonalInventory.UPCSearch.UPCSearchSoap.BeginGetProduct(PersonalInventory.UPCSearch.GetProductRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProduct(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetProduct(string upc, string accesstoken, System.AsyncCallback callback, object asyncState) {
            PersonalInventory.UPCSearch.GetProductRequest inValue = new PersonalInventory.UPCSearch.GetProductRequest();
            inValue.Body = new PersonalInventory.UPCSearch.GetProductRequestBody();
            inValue.Body.upc = upc;
            inValue.Body.accesstoken = accesstoken;
            return ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).BeginGetProduct(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonalInventory.UPCSearch.GetProductResponse PersonalInventory.UPCSearch.UPCSearchSoap.EndGetProduct(System.IAsyncResult result) {
            return base.Channel.EndGetProduct(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetProduct(System.IAsyncResult result) {
            PersonalInventory.UPCSearch.GetProductResponse retVal = ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).EndGetProduct(result);
            return retVal.Body.GetProductResult;
        }
        
        private System.IAsyncResult OnBeginGetProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string upc = ((string)(inValues[0]));
            string accesstoken = ((string)(inValues[1]));
            return this.BeginGetProduct(upc, accesstoken, callback, asyncState);
        }
        
        private object[] OnEndGetProduct(System.IAsyncResult result) {
            string retVal = this.EndGetProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductCompleted(object state) {
            if ((this.GetProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductCompleted(this, new GetProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductAsync(string upc, string accesstoken) {
            this.GetProductAsync(upc, accesstoken, null);
        }
        
        public void GetProductAsync(string upc, string accesstoken, object userState) {
            if ((this.onBeginGetProductDelegate == null)) {
                this.onBeginGetProductDelegate = new BeginOperationDelegate(this.OnBeginGetProduct);
            }
            if ((this.onEndGetProductDelegate == null)) {
                this.onEndGetProductDelegate = new EndOperationDelegate(this.OnEndGetProduct);
            }
            if ((this.onGetProductCompletedDelegate == null)) {
                this.onGetProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductDelegate, new object[] {
                        upc,
                        accesstoken}, this.onEndGetProductDelegate, this.onGetProductCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PersonalInventory.UPCSearch.UPCSearchSoap.BeginGetProductJSON(PersonalInventory.UPCSearch.GetProductJSONRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductJSON(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetProductJSON(string upc, string accesstoken, System.AsyncCallback callback, object asyncState) {
            PersonalInventory.UPCSearch.GetProductJSONRequest inValue = new PersonalInventory.UPCSearch.GetProductJSONRequest();
            inValue.Body = new PersonalInventory.UPCSearch.GetProductJSONRequestBody();
            inValue.Body.upc = upc;
            inValue.Body.accesstoken = accesstoken;
            return ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).BeginGetProductJSON(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonalInventory.UPCSearch.GetProductJSONResponse PersonalInventory.UPCSearch.UPCSearchSoap.EndGetProductJSON(System.IAsyncResult result) {
            return base.Channel.EndGetProductJSON(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetProductJSON(System.IAsyncResult result) {
            PersonalInventory.UPCSearch.GetProductJSONResponse retVal = ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).EndGetProductJSON(result);
            return retVal.Body.GetProductJSONResult;
        }
        
        private System.IAsyncResult OnBeginGetProductJSON(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string upc = ((string)(inValues[0]));
            string accesstoken = ((string)(inValues[1]));
            return this.BeginGetProductJSON(upc, accesstoken, callback, asyncState);
        }
        
        private object[] OnEndGetProductJSON(System.IAsyncResult result) {
            string retVal = this.EndGetProductJSON(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductJSONCompleted(object state) {
            if ((this.GetProductJSONCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductJSONCompleted(this, new GetProductJSONCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductJSONAsync(string upc, string accesstoken) {
            this.GetProductJSONAsync(upc, accesstoken, null);
        }
        
        public void GetProductJSONAsync(string upc, string accesstoken, object userState) {
            if ((this.onBeginGetProductJSONDelegate == null)) {
                this.onBeginGetProductJSONDelegate = new BeginOperationDelegate(this.OnBeginGetProductJSON);
            }
            if ((this.onEndGetProductJSONDelegate == null)) {
                this.onEndGetProductJSONDelegate = new EndOperationDelegate(this.OnEndGetProductJSON);
            }
            if ((this.onGetProductJSONCompletedDelegate == null)) {
                this.onGetProductJSONCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductJSONCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductJSONDelegate, new object[] {
                        upc,
                        accesstoken}, this.onEndGetProductJSONDelegate, this.onGetProductJSONCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PersonalInventory.UPCSearch.UPCSearchSoap.BeginValidate(PersonalInventory.UPCSearch.ValidateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginValidate(string upc, string accesstoken, System.AsyncCallback callback, object asyncState) {
            PersonalInventory.UPCSearch.ValidateRequest inValue = new PersonalInventory.UPCSearch.ValidateRequest();
            inValue.Body = new PersonalInventory.UPCSearch.ValidateRequestBody();
            inValue.Body.upc = upc;
            inValue.Body.accesstoken = accesstoken;
            return ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).BeginValidate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonalInventory.UPCSearch.ValidateResponse PersonalInventory.UPCSearch.UPCSearchSoap.EndValidate(System.IAsyncResult result) {
            return base.Channel.EndValidate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndValidate(System.IAsyncResult result) {
            PersonalInventory.UPCSearch.ValidateResponse retVal = ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).EndValidate(result);
            return retVal.Body.ValidateResult;
        }
        
        private System.IAsyncResult OnBeginValidate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string upc = ((string)(inValues[0]));
            string accesstoken = ((string)(inValues[1]));
            return this.BeginValidate(upc, accesstoken, callback, asyncState);
        }
        
        private object[] OnEndValidate(System.IAsyncResult result) {
            string retVal = this.EndValidate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidateCompleted(object state) {
            if ((this.ValidateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidateCompleted(this, new ValidateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidateAsync(string upc, string accesstoken) {
            this.ValidateAsync(upc, accesstoken, null);
        }
        
        public void ValidateAsync(string upc, string accesstoken, object userState) {
            if ((this.onBeginValidateDelegate == null)) {
                this.onBeginValidateDelegate = new BeginOperationDelegate(this.OnBeginValidate);
            }
            if ((this.onEndValidateDelegate == null)) {
                this.onEndValidateDelegate = new EndOperationDelegate(this.OnEndValidate);
            }
            if ((this.onValidateCompletedDelegate == null)) {
                this.onValidateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidateCompleted);
            }
            base.InvokeAsync(this.onBeginValidateDelegate, new object[] {
                        upc,
                        accesstoken}, this.onEndValidateDelegate, this.onValidateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PersonalInventory.UPCSearch.UPCSearchSoap.BeginConvertToUPCA(PersonalInventory.UPCSearch.ConvertToUPCARequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConvertToUPCA(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginConvertToUPCA(string upce, string accesstoken, System.AsyncCallback callback, object asyncState) {
            PersonalInventory.UPCSearch.ConvertToUPCARequest inValue = new PersonalInventory.UPCSearch.ConvertToUPCARequest();
            inValue.Body = new PersonalInventory.UPCSearch.ConvertToUPCARequestBody();
            inValue.Body.upce = upce;
            inValue.Body.accesstoken = accesstoken;
            return ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).BeginConvertToUPCA(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonalInventory.UPCSearch.ConvertToUPCAResponse PersonalInventory.UPCSearch.UPCSearchSoap.EndConvertToUPCA(System.IAsyncResult result) {
            return base.Channel.EndConvertToUPCA(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndConvertToUPCA(System.IAsyncResult result) {
            PersonalInventory.UPCSearch.ConvertToUPCAResponse retVal = ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).EndConvertToUPCA(result);
            return retVal.Body.ConvertToUPCAResult;
        }
        
        private System.IAsyncResult OnBeginConvertToUPCA(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string upce = ((string)(inValues[0]));
            string accesstoken = ((string)(inValues[1]));
            return this.BeginConvertToUPCA(upce, accesstoken, callback, asyncState);
        }
        
        private object[] OnEndConvertToUPCA(System.IAsyncResult result) {
            string retVal = this.EndConvertToUPCA(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConvertToUPCACompleted(object state) {
            if ((this.ConvertToUPCACompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConvertToUPCACompleted(this, new ConvertToUPCACompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConvertToUPCAAsync(string upce, string accesstoken) {
            this.ConvertToUPCAAsync(upce, accesstoken, null);
        }
        
        public void ConvertToUPCAAsync(string upce, string accesstoken, object userState) {
            if ((this.onBeginConvertToUPCADelegate == null)) {
                this.onBeginConvertToUPCADelegate = new BeginOperationDelegate(this.OnBeginConvertToUPCA);
            }
            if ((this.onEndConvertToUPCADelegate == null)) {
                this.onEndConvertToUPCADelegate = new EndOperationDelegate(this.OnEndConvertToUPCA);
            }
            if ((this.onConvertToUPCACompletedDelegate == null)) {
                this.onConvertToUPCACompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConvertToUPCACompleted);
            }
            base.InvokeAsync(this.onBeginConvertToUPCADelegate, new object[] {
                        upce,
                        accesstoken}, this.onEndConvertToUPCADelegate, this.onConvertToUPCACompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PersonalInventory.UPCSearch.UPCSearchSoap.BeginGenerateBarcode(PersonalInventory.UPCSearch.GenerateBarcodeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGenerateBarcode(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGenerateBarcode(string upc, System.AsyncCallback callback, object asyncState) {
            PersonalInventory.UPCSearch.GenerateBarcodeRequest inValue = new PersonalInventory.UPCSearch.GenerateBarcodeRequest();
            inValue.Body = new PersonalInventory.UPCSearch.GenerateBarcodeRequestBody();
            inValue.Body.upc = upc;
            return ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).BeginGenerateBarcode(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonalInventory.UPCSearch.GenerateBarcodeResponse PersonalInventory.UPCSearch.UPCSearchSoap.EndGenerateBarcode(System.IAsyncResult result) {
            return base.Channel.EndGenerateBarcode(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGenerateBarcode(System.IAsyncResult result) {
            PersonalInventory.UPCSearch.GenerateBarcodeResponse retVal = ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).EndGenerateBarcode(result);
            return retVal.Body.GenerateBarcodeResult;
        }
        
        private System.IAsyncResult OnBeginGenerateBarcode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string upc = ((string)(inValues[0]));
            return this.BeginGenerateBarcode(upc, callback, asyncState);
        }
        
        private object[] OnEndGenerateBarcode(System.IAsyncResult result) {
            string retVal = this.EndGenerateBarcode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGenerateBarcodeCompleted(object state) {
            if ((this.GenerateBarcodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GenerateBarcodeCompleted(this, new GenerateBarcodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GenerateBarcodeAsync(string upc) {
            this.GenerateBarcodeAsync(upc, null);
        }
        
        public void GenerateBarcodeAsync(string upc, object userState) {
            if ((this.onBeginGenerateBarcodeDelegate == null)) {
                this.onBeginGenerateBarcodeDelegate = new BeginOperationDelegate(this.OnBeginGenerateBarcode);
            }
            if ((this.onEndGenerateBarcodeDelegate == null)) {
                this.onEndGenerateBarcodeDelegate = new EndOperationDelegate(this.OnEndGenerateBarcode);
            }
            if ((this.onGenerateBarcodeCompletedDelegate == null)) {
                this.onGenerateBarcodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGenerateBarcodeCompleted);
            }
            base.InvokeAsync(this.onBeginGenerateBarcodeDelegate, new object[] {
                        upc}, this.onEndGenerateBarcodeDelegate, this.onGenerateBarcodeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PersonalInventory.UPCSearch.UPCSearchSoap.BeginSuggestProduct(PersonalInventory.UPCSearch.SuggestProductRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSuggestProduct(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSuggestProduct(string upc, string productnamewithmanufacturer, string productattribute, string accesstoken, System.AsyncCallback callback, object asyncState) {
            PersonalInventory.UPCSearch.SuggestProductRequest inValue = new PersonalInventory.UPCSearch.SuggestProductRequest();
            inValue.Body = new PersonalInventory.UPCSearch.SuggestProductRequestBody();
            inValue.Body.upc = upc;
            inValue.Body.productnamewithmanufacturer = productnamewithmanufacturer;
            inValue.Body.productattribute = productattribute;
            inValue.Body.accesstoken = accesstoken;
            return ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).BeginSuggestProduct(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonalInventory.UPCSearch.SuggestProductResponse PersonalInventory.UPCSearch.UPCSearchSoap.EndSuggestProduct(System.IAsyncResult result) {
            return base.Channel.EndSuggestProduct(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndSuggestProduct(System.IAsyncResult result) {
            PersonalInventory.UPCSearch.SuggestProductResponse retVal = ((PersonalInventory.UPCSearch.UPCSearchSoap)(this)).EndSuggestProduct(result);
            return retVal.Body.SuggestProductResult;
        }
        
        private System.IAsyncResult OnBeginSuggestProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string upc = ((string)(inValues[0]));
            string productnamewithmanufacturer = ((string)(inValues[1]));
            string productattribute = ((string)(inValues[2]));
            string accesstoken = ((string)(inValues[3]));
            return this.BeginSuggestProduct(upc, productnamewithmanufacturer, productattribute, accesstoken, callback, asyncState);
        }
        
        private object[] OnEndSuggestProduct(System.IAsyncResult result) {
            string retVal = this.EndSuggestProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSuggestProductCompleted(object state) {
            if ((this.SuggestProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SuggestProductCompleted(this, new SuggestProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SuggestProductAsync(string upc, string productnamewithmanufacturer, string productattribute, string accesstoken) {
            this.SuggestProductAsync(upc, productnamewithmanufacturer, productattribute, accesstoken, null);
        }
        
        public void SuggestProductAsync(string upc, string productnamewithmanufacturer, string productattribute, string accesstoken, object userState) {
            if ((this.onBeginSuggestProductDelegate == null)) {
                this.onBeginSuggestProductDelegate = new BeginOperationDelegate(this.OnBeginSuggestProduct);
            }
            if ((this.onEndSuggestProductDelegate == null)) {
                this.onEndSuggestProductDelegate = new EndOperationDelegate(this.OnEndSuggestProduct);
            }
            if ((this.onSuggestProductCompletedDelegate == null)) {
                this.onSuggestProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSuggestProductCompleted);
            }
            base.InvokeAsync(this.onBeginSuggestProductDelegate, new object[] {
                        upc,
                        productnamewithmanufacturer,
                        productattribute,
                        accesstoken}, this.onEndSuggestProductDelegate, this.onSuggestProductCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PersonalInventory.UPCSearch.UPCSearchSoap CreateChannel() {
            return new UPCSearchSoapClientChannel(this);
        }
        
        private class UPCSearchSoapClientChannel : ChannelBase<PersonalInventory.UPCSearch.UPCSearchSoap>, PersonalInventory.UPCSearch.UPCSearchSoap {
            
            public UPCSearchSoapClientChannel(System.ServiceModel.ClientBase<PersonalInventory.UPCSearch.UPCSearchSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetProduct(PersonalInventory.UPCSearch.GetProductRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetProduct", _args, callback, asyncState);
                return _result;
            }
            
            public PersonalInventory.UPCSearch.GetProductResponse EndGetProduct(System.IAsyncResult result) {
                object[] _args = new object[0];
                PersonalInventory.UPCSearch.GetProductResponse _result = ((PersonalInventory.UPCSearch.GetProductResponse)(base.EndInvoke("GetProduct", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductJSON(PersonalInventory.UPCSearch.GetProductJSONRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetProductJSON", _args, callback, asyncState);
                return _result;
            }
            
            public PersonalInventory.UPCSearch.GetProductJSONResponse EndGetProductJSON(System.IAsyncResult result) {
                object[] _args = new object[0];
                PersonalInventory.UPCSearch.GetProductJSONResponse _result = ((PersonalInventory.UPCSearch.GetProductJSONResponse)(base.EndInvoke("GetProductJSON", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginValidate(PersonalInventory.UPCSearch.ValidateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Validate", _args, callback, asyncState);
                return _result;
            }
            
            public PersonalInventory.UPCSearch.ValidateResponse EndValidate(System.IAsyncResult result) {
                object[] _args = new object[0];
                PersonalInventory.UPCSearch.ValidateResponse _result = ((PersonalInventory.UPCSearch.ValidateResponse)(base.EndInvoke("Validate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConvertToUPCA(PersonalInventory.UPCSearch.ConvertToUPCARequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ConvertToUPCA", _args, callback, asyncState);
                return _result;
            }
            
            public PersonalInventory.UPCSearch.ConvertToUPCAResponse EndConvertToUPCA(System.IAsyncResult result) {
                object[] _args = new object[0];
                PersonalInventory.UPCSearch.ConvertToUPCAResponse _result = ((PersonalInventory.UPCSearch.ConvertToUPCAResponse)(base.EndInvoke("ConvertToUPCA", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGenerateBarcode(PersonalInventory.UPCSearch.GenerateBarcodeRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GenerateBarcode", _args, callback, asyncState);
                return _result;
            }
            
            public PersonalInventory.UPCSearch.GenerateBarcodeResponse EndGenerateBarcode(System.IAsyncResult result) {
                object[] _args = new object[0];
                PersonalInventory.UPCSearch.GenerateBarcodeResponse _result = ((PersonalInventory.UPCSearch.GenerateBarcodeResponse)(base.EndInvoke("GenerateBarcode", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSuggestProduct(PersonalInventory.UPCSearch.SuggestProductRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SuggestProduct", _args, callback, asyncState);
                return _result;
            }
            
            public PersonalInventory.UPCSearch.SuggestProductResponse EndSuggestProduct(System.IAsyncResult result) {
                object[] _args = new object[0];
                PersonalInventory.UPCSearch.SuggestProductResponse _result = ((PersonalInventory.UPCSearch.SuggestProductResponse)(base.EndInvoke("SuggestProduct", _args, result)));
                return _result;
            }
        }
    }
}
